name: Release
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        required: true
        description: Bump up to [patch / minor / major]
        options:
          - patch
          - minor
          - major
        default: minor

concurrency: ${{ github.workflow }}

permissions: {}

jobs:
  call:
    uses: tmknom/release-workflows/.github/workflows/go.yml@2de83676a3f71bf5b1e0f14ce6b268e95d87ae77 # v0.9.5
    with:
      bump-level: ${{ inputs.bump-level }}
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
